# Generated by Django 5.2.7 on 2025-11-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='used_storage',
            field=models.BigIntegerField(default=0),
        ),
    ]
